#!/bin/sh
#export LC_ALL=C
HOST=localhost
PORT=4321
export LANG=en.US.UTF-8
export LANG=ta_IN.UTF-8

LANG=en_US

lang="$(zenity --entry --entry-text="Enter 1 for Tamil ; 2 for English" --text="Enter preffered language")"
if [ "$lang" -eq "1" ]
then
{
LANG=ta_IN
Variable1=$(zenity --entry --entry-text="type" --text="கண்டம் சேர்க்கவும்")
Variable2=$(zenity --entry --entry-text="type" --text="பகுதி சேர்க்கவும்")
Variable3="$Variable1/$Variable2"
echo $Variable3|nc $HOST $PORT
export TZ="$Variable1"/"$Variable2"
Display=$(date)
zenity --info --text="$Display"
}
elif [ "$lang" -eq "2" ]
then
{
export LANG=en.US.UTF-8
LANG=en_US
Variable1=$(zenity --entry --entry-text="Enter Continent" --text="Enter Continent")
Variable2=$(zenity --entry --entry-text="Enter Region" --text="Enter Region")
export TZ="$Variable1"/"$Variable2"
Display=$(date)
zenity --info --text="$Display"
}
fi
